### ISSUE TITLE
ČT

### ISSUE THREAD

**Issue by Jebacka** [znelkytv/IPTV-Czech#3]
https://sktv-forwarders.7m.pl/get.php?x=CTsport
https://sktv-forwarders.7m.pl/get.php?x=CT_D
https://sktv-forwarders.7m.pl/get.php?x=CTart
https://sktv-forwarders.7m.pl/get.php?x=CTsportPlus
https://sktv-forwarders.7m.pl/get.php?x=CT24
https://sktv-forwarders.7m.pl/get.php?x=CT2
https://sktv-forwarders.7m.pl/get.php?x=CT1

**Comment by znelkytv** [comment]
Děkuji Vám, ale tento odkaz některé přehrávače nepodporují.
